[package]
name = "java-jni-extras"
version = "0.1.0"
repository = "https://github.com/westbot657/java-jni-extras"
authors = ["westbot <82739021+westbot657@users.noreply.github.com>"]
description = "A collection of helper macros for use with jni"
edition = "2024"
license = "MIT"
readme = "README.md"

[dependencies]
java-jni-extras-proc = "0.1.0"
jni = "0.22.4"
